name: Coverage Report

on:
  pull_request_target:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
      - name: Report Test Coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          test-script: yarn test:all
          package-manager: yarn
          prnumber: ${{ steps.findPr.outputs.number }}
          annotations: coverage
